apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - name: authelia
          image: authelia/authelia:latest
          ports:
            - containerPort: 9091           
          volumeMounts:
            - name: config
              mountPath: /var/opt/authelia
            - name: users-db
              mountPath: /var/opt/users_database
              subPath: users_database
      volumes:
        - name: config
          configMap:values
            name: values.yml
        - name: users_databases
          configMap:
            name: users-database
