apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - name: authelia
          image: authelia/authelia:latest
          ports:
            - containerPort: 9091
 	volumeMounts:
        - name: config-volume
          mountPath: /etc/authelia
        - name: dbvolume
          mountPath: /var/lib/authelia       
      volumes:
      - name: dbvolume
        emptyDir:
          {}
      - name: config-volume
        configMap:
          name: authelia-config
          items:
          - key: values.yml
            path: values.yml
          - key: users_batabases.yaml
            path: users_database.yaml 
