apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yml: |
    server:
      host: 0.0.0.0
      port: 9091
    log:
      level: info
      format: text
    totp:
      issuer: example.com
    storage:
      local:
        path: /config/db.sqlite3
    authentication_backend:
      file:
        path: /config/users_database.yml
    access_control:
      default_policy: deny
      rules:
        - domain: example.com
          policy: two_factor
    session:
      name: authelia_session
      secret: "toto!!!!"
      expiration: 3600
      inactivity: 300
      domain: example.com
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    notifier:
      smtp:
        username: test@example.com
        password: password
        host: smtp.example.com
        port: 587
        sender: test@example.com
        secure: starttls
