---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
  namespace: nextcloud
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nextcloud
            image: nextcloud:25.0.3-apache
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl https://your.nextcloud.domain/cron.php
          restartPolicy: OnFailure

