apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: nextcloud-deployment
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cinder-classic #longhorn
  resources:
    requests:
      storage: 2Gi
