apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv-nfs # < name of the persisant volume ("pv") in kubenetes
  namespace: nextcloud      # < namespace where to place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi            # < max. size we reserve for the pv
  accessModes:
    - ReadWriteOnce         # < One pod can write to storage
  persistentVolumeReclaimPolicy: Retain # < the persistent volume can be reclaimed
  nfs:
    path: /volume1/data/nextcloud-db  # < Name of your NFS share with subfolder
    server: xxx.xxx.xxx.xxx               # < IP number of your NFS server             
    readOnly: false
