apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-server-pv-nfs
  namespace: nextcloud
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: xxx.xxx.xxx.xxx
    path: /volume1/data/nextcloud-server
    readOnly: false
