repo:
  name: grafana
  url: https://grafana.github.io/helm-charts

upgrade:
  install: true
  atomic: true
  timeout: 300s

namespace:
  name: grafana-cloud
  create: true

cluster:
  name: cluster-esgi
externalServices:
  prometheus:
    host: https://prometheus-prod-01-eu-west-0.grafana.net
    basicAuth:
      username: "569033"
      password: REPLACE_WITH_ACCESS_POLICY_TOKEN
  loki:
    host: https://logs-prod-eu-west-0.grafana.net
    basicAuth:
      username: "283486"
      password: REPLACE_WITH_ACCESS_POLICY_TOKEN
  tempo:
    host: https://tempo-eu-west-0.grafana.net:443
    basicAuth:
      username: "279999"
      password: REPLACE_WITH_ACCESS_POLICY_TOKEN
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: cluster-esgi
    prometheus:
      external:
        url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}